name: Content Refresh

on:
  schedule:
    - cron: '0 3 * * *'  # Her gün saat 03:00'te
  workflow_dispatch:

jobs:
  refresh-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update dates and versions
        run: |
          TODAY=$(date '+%Y-%m-%d')
          YEAR=$(date '+%Y')
          
          # Update copyright year
          sed -i "s/Copyright (c) [0-9]* MonoFarm/Copyright (c) $YEAR MonoFarm/g" LICENSE
          
          # Update game version references
          sed -i "s/best crypto farming game [0-9]*/best crypto farming game $YEAR/g" README.md
          sed -i "s/best crypto farming game [0-9]*/best crypto farming game $YEAR/g" docs/index.html
          
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add LICENSE README.md docs/index.html
          git commit -m "📅 Update dates and versions" || exit 0
          git push
