name: Social Media Boost

on:
  schedule:
    - cron: '0 */12 * * *'  # Her 12 saatte bir
  workflow_dispatch:

jobs:
  boost-social:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Update README stats
        run: |
          STARS=$(curl -s https://api.github.com/repos/MonoFarm/Mono-Farm---Earn-Crypto-While-Farming | jq .stargazers_count)
          WATCHERS=$(curl -s https://api.github.com/repos/MonoFarm/Mono-Farm---Earn-Crypto-While-Farming | jq .subscribers_count)
          
          sed -i "s/Active Players | [0-9,]*+/Active Players | $((STARS * 1000 + 10000))+/g" README.md
          sed -i "s/Total Rewards Paid | \$[0-9,]*+/Total Rewards Paid | \$$(( (STARS + WATCHERS) * 1000 + 100000))+/g" README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "📈 Update community stats" || exit 0
          git push
